version: "3.8"
services:
  server:
    image: zkfmapf123/node-fluentd:5.0
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        tag: server
    networks:
      - driver-bridge
    depends_on:
      - fluentd
  fluentd:
    build:
      context: .
      dockerfile: fluentd.Dockerfile
    container_name: fluentd
    hostname: fluentd
    restart: always
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "9800:9800"
    networks:
      - driver-bridge

networks:
  driver-bridge:
    driver: bridge
