version: "3.8"
services:
  fluentd:
    build:
      context: .
      dockerfile: fluentd.Dockerfile
    container_name: fluentd
    restart: always
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "9800:9800"
